

### SECRET ROUTE
GET http://localhost:3000/secret

### LOG OUT
GET http://localhost:3000/logout


### REGISTER USER
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "root1",
    "password": "toor"
}

### LOGIN SUCCESS
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "root1",
    "password": "toor"
}

### LOGIN FAILURE USER NOT EXIST
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "tutu",
    "password": "tutu"
}

### LOGIN FAILURE WRONG PASSWORD
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "root1",
    "password": "toorA"
}